language: cpp
matrix:
  allow_failures:
    - env: COMPILER=g++-4.7
    - os: osx
    
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.7']
      env: COMPILER=g++-4.7  

  
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: COMPILER=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9
      
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5
      
    - os: linux
      compiler: clang
      env: COMPILER=clang++
      
    - os: osx
      compiler: clang
      env: COMPILER=clang++

before_script:
  - mkdir build
  - cd build
  - cmake -G"Unix Makefiles" -D CMAKE_CXX_COMPILER=$COMPILER -D CMAKE_BUILD_TYPE=Debug -D ENABLE_TEST=ON -D CMAKE_INSTALL_PREFIX=../release ..

script: 
  - cmake --build . --config Debug
  - ctest -V -C Debug
  
branches:
  only:
    - master
    
notifications:
  email:
    recipients:
      - mkomm@cern.ch
    on_success: change
    on_failure: always

