branches:
  only:
    - master

environment:
  matrix:
    - os: Visual Studio 2015
    - os: Visual Studio 2013
    - os: Cygwin

clone_folder: c:\projects\CPX

before_build:
  - mkdir c:\projects\CPX\build
  - cd c:\projects\CPX\build
  - cmake -D ENABLE_TEST=ON ..

script:
  - cd c:\projects\CPX\build
  - msbuild CPX.sln
  - tree c:\projects\CPX\build

