branches:
  only:
    - master

os: Visual Studio 2015

# clone directory
clone_folder: c:\projects\CPX

configuration: Release

build:
  project: c:\projects\CPX\build\CPX.sln

# scripts to run before build
before_build:
  - mkdir c:\projects\CPX\build
  - cd c:\projects\CPX\build
  - cmake -D ENABLE_TEST=ON ..


