init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
    - master

environment:
  matrix:
    - os: Visual Studio 2015

clone_folder: c:\projects\CPX

before_build:
  - cmd: |
        mkdir c:\projects\CPX\build
        cd c:\projects\CPX\build
        cmake -D CMAKE_BUILD_TYPE=Debug -D ENABLE_TEST=ON -D CMAKE_INSTALL_PREFIX=c:\projects\CPX\release ..

build_script:
  - cmd: |
        cd c:\projects\CPX\build
        cmake --build . --config Debug

test_script:
  - cmd: |
        PATH=c:\projects\CPX\build;c:\projects\CPX\build\Debug;c:\projects\CPX\build\Debug\test;%PATH%
        cd c:\projects\CPX\build
        ctest -V -C Debug

    

