branches:
  only:
    - master

environment:
  matrix:
    - os: Visual Studio 2015

clone_folder: c:\projects\CPX

before_build:
  - mkdir c:\projects\CPX\build
  - cd c:\projects\CPX\build
  - cmake -G "NMake Makefiles" -D CMAKE_BUILD_TYPE=Debug -D ENABLE_TEST=ON -D CMAKE_INSTALL_PREFIX=c:\projects\CPX\release ..

build_script:
  - cd c:\projects\CPX\build
  - nmake install

test_script:
  - cd c:\projects\CPX\release\lib
  - ..\bin\cpx-test

notifications:
  - provider: Email
    to:
      - mkomm@cern.ch
    subject: 'Build {{status}}'
    message: "{{message}}, {{commitId}}"
    on_build_status_changed: true
    
